// Generated by python -m tools.generate_dummy_fixtures; edit common/dummy_fixtures.json.
#pragma once
#include <stddef.h>
#include <stdint.h>

namespace comms {
constexpr int16_t kDummyFixtures[][8] = {
  {0, 0, 1000, 0, 0, 0, 10, 20},
  {1200, -300, 850, 40, -20, 15, 600, 250},
  {-700, 950, 400, -80, 60, 25, 100, 900},
  {32767, -32768, -1, 0, 1, 123, -456, 789},
};
constexpr size_t kDummyFixtureCount = sizeof(kDummyFixtures) / sizeof(kDummyFixtures[0]);
}  // namespace comms
