"""Regenerate the firmware fixture table after editing common/dummy_fixtures.json."""
from pathlib import Path
from common.sensor import load_fixtures


def render_header():
    rows = load_fixtures()
    body = '\n'.join('  {' + ', '.join(map(str, row)) + '},' for row in rows)
    return ('// Generated by python -m tools.generate_dummy_fixtures; edit common/dummy_fixtures.json.\n'
            '#pragma once\n#include <stddef.h>\n#include <stdint.h>\n\nnamespace week7 {\n'
            'constexpr int16_t kDummyFixtures[][8] = {\n' + body + '\n};\n'
            'constexpr size_t kDummyFixtureCount = sizeof(kDummyFixtures) / sizeof(kDummyFixtures[0]);\n'
            '}  // namespace week7\n')


def main():
    path = Path(__file__).resolve().parents[1] / 'firmware/esp32/include/week7_fixtures.h'
    path.write_text(render_header(), encoding='utf-8', newline='\n')
    print(path)


if __name__ == '__main__':
    main()
